server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: NEVER

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app?useSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update

tokenSecret: "dkjfkdjagtwjsfj"

logging:
  level:
    root: debug




